# ·şÎñ¶Ë¿Ú
server:
  port: 8080
# jdbc
spring:
  datasource:
    password: 123456
    username: root
    url: jdbc:mysql://localhost:3306/gmall_study?characterEncoding=UTF-8
# mybtaisÅäÖÃ
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
